# Generated by Django 2.0.5 on 2020-11-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triumphbike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
